huh:
    encore:
        entries:
            - { name: contao-utils-bundle-arrays, file: "vendor/heimrichhannot/contao-utils-bundle/src/Resources/public/js/arrays.es6.js" }
            - { name: contao-utils-bundle-url, file: "vendor/heimrichhannot/contao-utils-bundle/src/Resources/public/js/url.es6.js" }
            - { name: contao-utils-bundle-util, file: "vendor/heimrichhannot/contao-utils-bundle/src/Resources/public/js/util.es6.js" }