services:
    # util services
    huh.utils.array:
        class: HeimrichHannot\UtilsBundle\Arrays\ArrayUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.cache.remote_image_cache:
        class: HeimrichHannot\UtilsBundle\Cache\RemoteImageCache
        public: true
        arguments:
            - "@contao.framework"
            - "@service_container"
    huh.utils.code:
        class: HeimrichHannot\UtilsBundle\Security\CodeUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.encryption:
        class: HeimrichHannot\UtilsBundle\Security\EncryptionUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.container:
        class: HeimrichHannot\UtilsBundle\Container\ContainerUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.database:
        class: HeimrichHannot\UtilsBundle\Database\DatabaseUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.date:
        class: HeimrichHannot\UtilsBundle\Date\DateUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.dca:
        class: HeimrichHannot\UtilsBundle\Dca\DcaUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.file:
        class: HeimrichHannot\UtilsBundle\File\FileUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.form:
        class: HeimrichHannot\UtilsBundle\Form\FormUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.image:
        class: HeimrichHannot\UtilsBundle\Image\Image
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.model:
        class: HeimrichHannot\UtilsBundle\Model\ModelUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.request.curl:
        class: HeimrichHannot\UtilsBundle\Request\CurlRequestUtil
        public: true
        arguments:
            - "@contao.framework"
            - "@service_container"
    huh.utils.string:
        class: HeimrichHannot\UtilsBundle\String\StringUtil
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.url:
        class: HeimrichHannot\UtilsBundle\Url\UrlUtil
        public: true
        arguments:
            - "@contao.framework"
    # choice
    huh.utils.choice.field:
        class: HeimrichHannot\UtilsBundle\Choice\FieldChoice
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.choice.data_container:
        class: HeimrichHannot\UtilsBundle\Choice\DataContainerChoice
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.choice.message:
        class: HeimrichHannot\UtilsBundle\Choice\MessageChoice
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.choice.model_instance:
        class: HeimrichHannot\UtilsBundle\Choice\ModelInstanceChoice
        public: true
        arguments:
            - "@contao.framework"
    huh.utils.routing:
      class: HeimrichHannot\UtilsBundle\Request\RoutingUtil
      public: true
      arguments:
        - "@router"
        - "@request_stack"
        - "@security.csrf.token_manager"
        - "%contao.csrf_token_name%"